//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string razonSocial { get; set; }
        public string nombreFantasia { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string personeria { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string emailFacturacon { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public byte activo { get; set; }
    }
}
