//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobros
    {
        public long id { get; set; }
        public string nro_factura { get; set; }
        public System.DateTime fecha_factura { get; set; }
        public double monto { get; set; }
        public Nullable<double> cobro_parcial { get; set; }
        public string observaciones { get; set; }
        public Nullable<double> subtotal_recibo { get; set; }
        public double total { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public Nullable<byte> activo { get; set; }
        public int cliente_id { get; set; }
        public long nro_recibo { get; set; }
    }
}
