//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public long id { get; set; }
        public long proveedor_id { get; set; }
        public int tipo_comprobante_id { get; set; }
        public string nro_factura { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public System.DateTime fecha_contable { get; set; }
        public Nullable<System.DateTime> vencimiento_1 { get; set; }
        public Nullable<System.DateTime> vencimiento_2 { get; set; }
        public double importe { get; set; }
        public Nullable<double> descuento_global { get; set; }
        public byte activo { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_user_id { get; set; }
    }
}
