//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte expense_id { get; set; }
        public System.DateTime register_date { get; set; }
        public Nullable<long> update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> create_user_id { get; set; }
        public Nullable<System.DateTime> date_expense { get; set; }
        public Nullable<decimal> amount { get; set; }
        public byte[] image { get; set; }
        public Nullable<byte> activo { get; set; }
        public string path_url { get; set; }
        public string name_file { get; set; }
        public double amount_money { get; set; }
        public string selling_point { get; set; }
        public string nro_comprobante { get; set; }
        public string cuit_cuil { get; set; }
        public string nro_cuit_cuil { get; set; }
        public string denominacion_emisor { get; set; }
        public Nullable<double> imp_neto_gravado { get; set; }
        public Nullable<double> imp_neto_no_gravado { get; set; }
        public Nullable<double> imp_op_exentas { get; set; }
        public Nullable<double> iva { get; set; }
        public Nullable<double> importe_total { get; set; }
        public int tipo_comprobante_id { get; set; }
        public Nullable<long> proveedor_id { get; set; }
        public string periodo { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public string pay_state { get; set; }
    
        public virtual expense_type expense_type { get; set; }
    }
}
