//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_proveedores
    {
        public long id { get; set; }
        public string tipo_factura { get; set; }
        public Nullable<long> update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<long> create_user_id { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public int tipo_comprobante_id { get; set; }
        public Nullable<long> proveedor_id { get; set; }
        public string punto_venta { get; set; }
        public string nro_comprobante { get; set; }
        public string cuit_cuil { get; set; }
        public string nro_cuit_cuil { get; set; }
        public string description { get; set; }
        public Nullable<double> imp_neto_gravado { get; set; }
        public Nullable<double> imp_neto_no_gravado { get; set; }
        public Nullable<double> imp_op_exentas { get; set; }
        public Nullable<double> iva { get; set; }
        public double importe_total { get; set; }
        public string name_file { get; set; }
        public byte activo { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public string periodo { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<long> profesional_id { get; set; }
    }
}
