//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_pago_cab
    {
        public long id { get; set; }
        public long profesional_id { get; set; }
        public double importe_total { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<byte> activo { get; set; }
        public Nullable<int> create_user_id { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
