//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesional
    {
        public int id { get; set; }
        public int product_service_id { get; set; }
        public string nombre { get; set; }
        public string matricula { get; set; }
        public string cuit { get; set; }
        public string domicilio { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public Nullable<byte> activo { get; set; }
        public Nullable<int> tipo_facturacion { get; set; }
        public string nro_cuit { get; set; }
        public string cbu { get; set; }
        public string banco { get; set; }
        public string nro_cuenta { get; set; }
        public string alias { get; set; }
    }
}
