//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_order
    {
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int product_service_id { get; set; }
        public Nullable<double> cantidad { get; set; }
        public string nombre_paciente { get; set; }
        public Nullable<int> social_work_id { get; set; }
        public Nullable<int> profesional_id { get; set; }
        public string motivo_eliminacion { get; set; }
        public int status_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_user_id { get; set; }
    }
}
